server:
  port: 8080
spring:
  datasource:
    username: root
    password: 33333@zbx
    url: jdbc:mysql://localhost:3306/test?useSSL=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  resources:
    static-locations:classpath:static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html


mybatis:
  type-aliases-package: com.example.JavaEE.Bean
  mapper-locations: classpath:mappers/*.xml

