################ 项目基本配置 ################
server:
  port: 8011
  servlet:
    # 项目访问路径前缀
    context-path: /user
spring:
  application:
    # 注册到Eureka的服务名
    name: User
  datasource:
    username: root
    password: 33333@zbx
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  resources:
    static-locations:classpath:static/
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

mybatis:
  type-aliases-package: com.example.EurekaUser.Bean
  mapper-locations: classpath:mappers/*.xml

################ Eureka配置 ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
