################ 项目基本配置 ################
server:
  port: 8010
  servlet:
    # 项目访问路径前缀
    context-path: /gateway
spring:
  application:
    # 注册到Eureka的服务名
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      cors-configurations:
        #  允许跨域的路径（备注：/**表示所有路径）
        '[/**]':
          #  允许哪些请求源跨域（备注：allowCredentials为true时，allowedOrigins不能设置为“*”，会报错）
          allowedOriginPatterns:
            - "*"
          #             allowedOrigins: "*"
          #  是否携带cookie跨域
          allowCredentials: true
          #  允许哪种请求头跨域
          allowedHeaders: "*"
          #  允许哪种方法类型跨域（备注：这里我设置了GET、POST、PUT、DELETE、OPTIONS）
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
      routes:
        - id: user
          uri: http://127.0.0.1:8011
          predicates:
            - Path=/user/**
        - id: order
          uri: http://127.0.0.1:8012
          predicates:
            - Path=/order/**
        - id: trans
          uri: http://127.0.0.1:8013
          predicates:
            - Path=/trans/**

################ Eureka配置 ################
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
